hw3
nic11/kis-react pull request #1
Opened 2021-10-06 21:19 UTC by nic11

2021-10-09 16:57 UTC, dshuran requested changes
Просьба исправить ошибки и указать имя и фамилию, затем перезапросить моё ревью. Пока не понял, чья это работа.

2021-10-09 16:57 UTC, dshuran commented on src/Counter.js
> +    super();
Забыли props

2021-10-09 16:57 UTC, dshuran commented on src/Counter.js
> +        if (this.state.count < 10) {
А если count > 10, то эта функция так и будет бесконечно выполняться каждую секунду. Предлагается очищать таймер, если count > 10

2021-10-09 16:57 UTC, dshuran commented on src/Counter.js
> +        {parseInt(this.props.start) + this.state.count}
Можно сразу передавать число в JSX из компонента App, тогда не придётся здесь парсить

2021-10-09 16:57 UTC, dshuran commented on src/Counter.js
> +        {this.props.description}<br />
br - не очень хороший код стайл. Предлагается выполнять перенос на новую строку посредством CSS

2021-10-09 16:57 UTC, dshuran commented on src/App.js
> +        {this.counters}
Не совсем понятно, почему бы просто не вставить сюда компоненты без лишней переменной counters

2021-10-09 16:57 UTC, dshuran commented on src/Counter.js
> +      <div className="Counter">
Просьба сделать достойную стилизацию, как в примере. Сейчас её нет вообще

2021-10-16 16:45 UTC, nic11 commented on src/Counter.js
> +      <div className="Counter">
Так норм?
![Screenshot from 2021-10-16 19-45-15](https://user-images.githubusercontent.com/11034375/137595560-05e211e0-8846-4584-8c87-409d6f24d908.png)

2021-10-16 16:47 UTC, nic11 commented
@dshuran Замечания поправил. А имя с фамилией забыл указать отдельно, но они у меня и так в профиле написаны и в коммитах

2021-10-16 18:50 UTC, dshuran approved these changes

2021-10-16 18:50 UTC, merged